[package]
name = "annotai"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-openai = "0.26.0"
base64 = "0.22.1"
clap = { version = "4.5.23", features = ["derive"] }
ffmpeg-next = "7.1.0"
image = "0.25.5"
tokio = { version = "1.42.0", features = ["full"] }
